# Generated by Django 2.2.6 on 2019-10-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clg_details',
            fields=[
                ('clg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clg_name', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=20)),
                ('University', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dym_render',
            fields=[
                ('My_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('My_id', models.CharField(max_length=20)),
                ('My_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.IntegerField()),
                ('obc', models.IntegerField()),
                ('sc', models.IntegerField()),
                ('st', models.IntegerField()),
                ('sbc', models.IntegerField()),
                ('vj_nt', models.IntegerField()),
                ('clg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_finder.clg_details')),
            ],
        ),
        migrations.CreateModel(
            name='cut_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=30)),
                ('Intake', models.IntegerField()),
                ('GOPENS', models.CharField(max_length=3)),
                ('GSCS', models.CharField(max_length=3)),
                ('GSTS', models.CharField(max_length=3)),
                ('GVJS', models.CharField(max_length=3)),
                ('GNT1S', models.CharField(max_length=3)),
                ('GNT2S', models.CharField(max_length=3)),
                ('GNT3S', models.CharField(max_length=3)),
                ('GOBCS', models.CharField(max_length=3)),
                ('LOPENS', models.CharField(max_length=3)),
                ('LSCS', models.CharField(max_length=3)),
                ('LSTS', models.CharField(max_length=3)),
                ('LVJS', models.CharField(max_length=3)),
                ('LNT1S', models.CharField(max_length=3)),
                ('LNT2S', models.CharField(max_length=3)),
                ('LNT3S', models.CharField(max_length=3)),
                ('LOBCS', models.CharField(max_length=3)),
                ('clg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_finder.clg_details')),
            ],
        ),
    ]
