# Generated by Django 2.2.5 on 2020-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='clg_details',
            fields=[
                ('clg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clg_name', models.CharField(max_length=1000)),
                ('District', models.CharField(max_length=20)),
                ('University', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cut_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id', models.IntegerField()),
                ('Department', models.CharField(max_length=300)),
                ('Intake', models.IntegerField()),
                ('GOPENS', models.CharField(max_length=20)),
                ('GSCS', models.CharField(max_length=20)),
                ('GSTS', models.CharField(max_length=20)),
                ('GVJS', models.CharField(max_length=20)),
                ('GNT1S', models.CharField(max_length=20)),
                ('GNT2S', models.CharField(max_length=20)),
                ('GNT3S', models.CharField(max_length=20)),
                ('GOBCS', models.CharField(max_length=20)),
                ('LOPENS', models.CharField(max_length=20)),
                ('LSCS', models.CharField(max_length=20)),
                ('LSTS', models.CharField(max_length=20)),
                ('LVJS', models.CharField(max_length=20)),
                ('LNT1S', models.CharField(max_length=20)),
                ('LNT2S', models.CharField(max_length=20)),
                ('LNT3S', models.CharField(max_length=20)),
                ('LOBCS', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id_id', models.IntegerField()),
                ('open', models.CharField(max_length=20)),
                ('obc', models.CharField(max_length=20)),
                ('sc', models.CharField(max_length=20)),
                ('st', models.CharField(max_length=20)),
                ('sbc', models.CharField(max_length=20)),
                ('vj', models.CharField(max_length=20)),
                ('nt', models.CharField(max_length=20)),
            ],
        ),
    ]
