# Generated by Django 2.2.5 on 2020-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_finder', '0002_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='rdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
