# Generated by Django 2.2.5 on 2020-02-20 15:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_data23',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user_data23',
            name='Phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
