# Generated by Django 2.2.5 on 2020-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data23',
            name='full_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
