# Generated by Django 2.2.5 on 2020-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200220_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data23',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user_data23',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
