# Generated by Django 2.2.5 on 2020-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_data23_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data23',
            name='password',
            field=models.CharField(max_length=20000),
        ),
    ]
