# Generated by Django 2.2.5 on 2020-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_data23_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data23',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_data23',
            name='profile_pic',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
