# Generated by Django 2.2.5 on 2020-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200503_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fav_college_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_data23',
            name='Phone_no',
            field=models.IntegerField(),
        ),
    ]
