# Generated by Django 2.2.5 on 2020-05-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_data23_staff_clg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data23',
            name='Rdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data23',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
