# Generated by Django 2.2.5 on 2020-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200505_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data23',
            name='instu_code',
            field=models.IntegerField(null=True),
        ),
    ]
