# Generated by Django 2.2.5 on 2020-05-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_data23_instu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data23',
            name='Phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
