# Generated by Django 2.2.5 on 2020-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200517_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data23',
            name='Phone_no',
            field=models.CharField(error_messages={'unique': 'User with this Phone number is already exists'}, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_data23',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this Email ID is already exists'}, max_length=254, unique=True),
        ),
    ]
